#!/usr/sbin/nft -f

table inet filtre {
    chain input {
        type filter hook input priority 0;
	
	# Accepter les connexions établies ou liées.
	ct state established,related accept

	# Accepter les adresses locales loopback.
	iif lo accept
	
        # Accepter FTP, SSH, HTTP et HTTPS sur la patte interne.
        ip saddr 192.168.10.0/24 ip daddr 192.168.10.1 tcp dport { 21, 49150-49200, 22, 5501, 5502 } accept

        # Accepter HTTP et HTTPS sur la patte externe.
 	ip daddr 10.0.0.10 tcp dport { 80, 443 }  accept
	
	# Bloquer les scans de ports.
        tcp flags & (fin | syn | rst | psh | ack | urg) == fin drop
        tcp flags & (fin | syn | rst | psh | ack | urg) == fin|psh|urg drop
        tcp flags & (fin | syn | rst | psh | ack | urg) == 0 drop

        drop

    }

    chain forward {
        type filter hook forward priority 0;
        drop
    }

    chain output {
        type filter hook output priority 0;
        accept
    }
}
